### W10D1 - Pratica

#### Esercizio 1: 
Data lista di liste, che tipo di struttura dati o matematica potrebbe rappresentare? Notare che tutte le liste "interne" sono della stessa dimensione.                                                                        
Come facciamo per accedere ad un elemento in particolare?

In [1]:
'''Potrebbe rappresentare una matrice o array bidimensionale -> devo trasformare le liste in array. 
In termini matematici, una matrice è una disposizione rettangolare di numeri in righe e colonne.'''

mat = [[0, 1, 2, 3, 4], 
       [5, 6, 7, 8, 9], 
       [10, 11, 12, 13, 14]] 

import numpy as np                                                         #Importo libreria NumPy, con alias 'np'

#Definisco una matrice 3x5
array_matrice = np.array(mat)                                              #Converto in un array numpy -> casting
print(f"La matrice è la seguente:\n{array_matrice}\n")                     #Stampo matrice, andando a capo per ogni riga

#Accesso all'elemento nella seconda riga e terza colonna
elemento = array_matrice[1][2]                                             #Questo accede all'elemento 7
print(f"L'elemento nella seconda riga e terza colonna è: {elemento}")

#Accesso all'elemento nella terza riga e quarta colonna
elemento = array_matrice[2][3]                                             #Questo accede all'elemento 13
print(f"L'elemento nella terza riga e quarta colonna è: {elemento}")

#Accesso all'elemento nella prima riga e seconda colonna
elemento = array_matrice[0][1]                                             #Questo accede all'elemento 1
print(f"L'elemento nella prima riga e seconda colonna è: {elemento}")

#Accesso all'elemento nella seconda riga e quinta colonna
elemento = array_matrice[1][4]                                             #Questo accede all'elemento 9
print(f"L'elemento nella seconda riga e quinta colonna è: {elemento}")

La matrice è la seguente:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

L'elemento nella seconda riga e terza colonna è: 7
L'elemento nella terza riga e quarta colonna è: 13
L'elemento nella prima riga e seconda colonna è: 1
L'elemento nella seconda riga e quinta colonna è: 9


In [2]:
'''Converto le singole liste in array, per poi sommarle tra loro. Creo poi un DataFrame con Pandas, con etichette di riga, 
per selezionare e stampare alcune righe, per usare l'indicizzazione basata su etichette (.loc[])
e l'indicizzazione basata su posizioni (.iloc[]).'''

mat = [[0, 1, 2, 3, 4], 
       [5, 6, 7, 8, 9], 
       [10, 11, 12, 13, 14]]                                              

array1 = np.array(mat[0])                                        #Converto prima riga matrice in un array -> casting
array2 = np.array(mat[1])                                        #Converto seconda riga matrice in un array -> casting
array3 = np.array(mat[2])                                        #Converto terza riga matrice in un array -> casting

somma_array = array1 + array2 + array3
print(f"La somma delle tre liste è: {somma_array}\n")            #Sommo tre array e stampo risultato

import pandas as pd                                              #Importo libreria Pandas, con alias 'pd'

#Creo DataFrame, utilizzando Pandas, con colonne 'A', 'B' e 'C' e etichette di riga '1', '2', '3', '4', '5'
mat_dataframe = pd.DataFrame({"A": [0, 1, 2, 3, 4], "B": [5, 6, 7, 8, 9], "C": [10, 11, 12, 13, 14]},
                             index=list("12345"))
display(mat_dataframe)                                           #Visualizzo DataFrame

print("\nLe ultime tre righe della colonna B:")
print(mat_dataframe.loc['3':'5', "B"], "\n")                     #Utilizzo indicizzazione basata su etichette (label-based indexing)
print("Il valore della prima colonna alla riga '3':")
print(mat_dataframe.iloc[-3, 0])                                 #Utilizzo indicizzazione basata su posizioni (position-based indexing)

La somma delle tre liste è: [15 18 21 24 27]



A  B   C
1  0  5  10
2  1  6  11
3  2  7  12
4  3  8  13
5  4  9  14


Le ultime tre righe della colonna B:
3    7
4    8
5    9
Name: B, dtype: int64 

Il valore della prima colonna alla riga '3':
2


#### Esercizio 2:
Importiamo il modulo math e proviamo a usare le funzioni .sin() .cos() .factorial() e la variabile .pi.

In [3]:
import math                                            #Importo libreria math

#Chiedo numero in input all'utente
numero = int(input("Inserisci un numero: "))           #Converto input utente in un intero
numero_radianti = math.radians(numero)                 #Converto numero in radianti

#Utilizzo funzione .sin(), per calcolare seno numero, indicato in radianti
seno = round(math.sin(numero_radianti), 2)             #Arrotondo risultato a due decimali
print(f"Il seno di {numero} è {seno}")                 #Stampo seno numero in radianti

#Utilizzo unzione cos(), per calcolare coseno numero, indicato in radianti
coseno = round(math.cos(numero_radianti), 2)           #Arrotondo risultato a due decimali
print(f"Il coseno di {numero} è {coseno}")             #Stampo coseno numero in radianti

#Utilizzo funzione factorial(), per calcolare fattoriale numero definito 
fattoriale = math.factorial(numero)                    #Calcolo prodotto di tutti numeri interi positivi, fino a n
print(f"Il fattoriale di {numero} è: {fattoriale}")    #Stampo attoriale numero   

#Utilizzo variabile pi, per stampare valore pi greco (circa 3.14159) -> non vuole parentesi 
pi_greco = round(math.pi, 2)                           #Arrotondo valore pi greco a due decimali 
print(f"Il valore di pi greco è: {pi_greco}")          #Stampo valore pi greco

Inserisci un numero:  8


Il seno di 8 è 0.14
Il coseno di 8 è 0.99
Il fattoriale di 8 è: 40320
Il valore di pi greco è: 3.14


#### Esercizio 3:
Proviamo a eseguire math.degrees(math.pi). Qual è e cosa significa il risultato?                                                         
Per saperne di più su questa funzione possiamo usare help(math.degrees).

In [4]:
gradi = math.degrees(math.pi)                           #Converto pi greco, da radianti a gradi
print(f"Il valore di pi greco in gradi è: {gradi}\n")   #Stampo risultato

#Utilizzo la funzione help(), per saperne di più su math.degrees()
help(math.degrees)                  #degrees(x, /) Convert angle x from radians to degrees [Converte l'angolo x da radianti a gradi.]

Il valore di pi greco in gradi è: 180.0

Help on built-in function degrees in module math:

degrees(x, /)
    Convert angle x from radians to degrees.



#### Esercizio 4:
L'azienda Object SpA ha creato una lista di quanti oggetti ha venduto ogni mese nell'ultimo anno.
Trasformiamola in un array e rispondiamo alle domande del CEO della Object SpA:  

Qual è stata la vendita massima mensile? E quella minima?                                                                             
Quali sono le vendite mensili maggiori di 4999 oggetti? E quante ne sono?                                                               
Quali sono le vendite minori di 3000 oggetti?                                                                                           
In media quanti oggetti sono stati venduti al mese?

In [5]:
#Lista vendite mensili
lst = [2000, 5500, 7200, 4320, 1280, 1900, 2500, 3900, 6410, 8150, 7100, 5350]
vendite = np.array(lst)                               #Trasformo lista in un array -> casting

vendita_max = vendite.max()                           #Vendita massima mensile
print(f"La vendita massima mensile è: {vendita_max}") #Stampo a video

vendita_min = vendite.min()                           #Vendita minima mensile
print(f"La vendita minima mensile è: {vendita_min}")  #Stampo a video

filtro = vendite > 4999                               #Masking ->  filtrare parti di dati 
vendite_over_4999 = vendite[filtro]                   #Vendite mensili maggiori di 4999 oggetti
print(f"Le vendite mensili maggiori di 4999 oggetti sono: {vendite_over_4999}")
print(f"Le vendite superiori a 4999 sono 4999 sono {len(vendite_over_4999)}")
#Per calcolare il numero di vendite superiori a 4999 oggetti, posso utilizzare anche np.sum(vendite_over_4999)

filtro = vendite < 3000                               #Masking ->  filtrare parti di dati
vendite_under_3000 = vendite[filtro]                  #Vendite mensili minori di 3000 oggetti
print(f"Le vendite mensili minori di 3000 oggetti sono: {vendite_under_3000}")

media_vendite = round(np.mean(vendite),2)             #Media vendite mensili, arrotondata a 2 decimali
print(f"In media, sono stati venduti {media_vendite} oggetti al mese.")  

La vendita massima mensile è: 8150
La vendita minima mensile è: 1280
Le vendite mensili maggiori di 4999 oggetti sono: [5500 7200 6410 8150 7100 5350]
Le vendite superiori a 4999 sono 4999 sono 6
Le vendite mensili minori di 3000 oggetti sono: [2000 1280 1900 2500]
In media, sono stati venduti 4634.17 oggetti al mese.


#### Esercizio 5:
Consideriamo il dizionario e la Series, possiamo accedere alle stesse informazioni nello stesso modo?                                    
Dunque qual è la differenza tra i due tipi di dato?                                                                                      
Cosa potremmo fare con la Series, che non possiamo fare con il dizionario?

In [6]:
fatturati_dict = {1997: 12_000, 1998: 15_000, 1999: 20_000, 2000: 23_000, 2001: 25_000, 2002: 17_000, 
                  2003: 14_000, 2004: 21_000}                               #Dizionario fatturati annuali, con _ per separare migliaia
fatturati_series = pd.Series([12_000, 15_000, 20_000, 23_000, 25_000, 17_000, 14_000, 21_000], 
                             index=range(1997, 2005))                       #Series con fatturati annuali e anni come indice

#Accesso ai valori
print(f"Il fatturato del 1997 dal dizionario è: {fatturati_dict[1997]}")    #Stampo valore 1997 dal 'dizionario'
print(f"Il fatturato del 1997 dalla Series è: {fatturati_series[1997]}\n")  #Stampo valore 1997 dalla 'Series'

#Calcolo della media
media = fatturati_series.mean()
print(f"La media dei fatturati é: {media}\n")                               #Stampo media fatturati

#Operazioni aritmetiche
print(f"Fatturati moltiplicati per 2:\n{fatturati_series * 2}\n")           #Stampo fatturati, moltiplicati per 2

#Filtraggio dei dati
filtrati = fatturati_series[fatturati_series > 20_000]
print(f"Fatturati maggiori di 20_000:\n{filtrati}\n")                       #Stampo fatturati, maggiori di 20_000

#Operazioni con altre Series
altra_series = pd.Series([1, 2, 3, 4, 5, 6, 7, 8], index=range(1997, 2005)) #Creo altra Series, con anni come indice
somma_series = fatturati_series + altra_series                              #Sommo due Series tra loro
print(f"Somma delle due Series:\n{somma_series}")                           #Stampo somma due Series

Il fatturato del 1997 dal dizionario è: 12000
Il fatturato del 1997 dalla Series è: 12000

La media dei fatturati é: 18375.0

Fatturati moltiplicati per 2:
1997    24000
1998    30000
1999    40000
2000    46000
2001    50000
2002    34000
2003    28000
2004    42000
dtype: int64

Fatturati maggiori di 20_000:
2000    23000
2001    25000
2004    21000
dtype: int64

Somma delle due Series:
1997    12001
1998    15002
1999    20003
2000    23004
2001    25005
2002    17006
2003    14007
2004    21008
dtype: int64


Entrambi i tipi di dato, dizionario e Series, permettono di accedere ai valori tramite le chiavi (o indici), ma ci sono alcune differenze fondamentali tra i due e alcune operazioni che possiamo fare con una Series, che non possiamo fare con un dizionario.

**Differenze principali**:
1) **Tipo di dato**:
* *Dizionario*: È una struttura dati nativa di Python, che mappa chiavi a valori (e non ha un ordine).
* *Series*: È una struttura dati di Pandas, che rappresenta una colonna di dati, con un indice.

2) **Operazioni e funzionalità**:
* *Dizionario*: È limitato alle operazioni di base come l'accesso, l'aggiornamento, l'aggiunta e la rimozione di elementi.
* *Series*: Offre molte più funzionalità, come operazioni aritmetiche vettoriali, metodi statistici, indicizzazione avanzata, e molto altro.

#### Esercizio 6:
L'azienda Object SpA ha un dataset con tutti gli stipendi dei dipendenti, memorizzato in un ndarray.                                   
L'azienda ci chiede di raddoppiare tutti gli stipendi; facciamolo in due modi -> con ciclo for e con il masking.

In [7]:
#Creo un array con gli stipendi
stipendi = np.array([100, 200, 300, 400, 500, 600, 700, 800, 900, 1000])  

#Con ciclo for
nuovi_stipendi = []                                          #Inizializzo lista vuota, per nuovi stipendi
                 
for stipendio in stipendi:                                   #Itero attraverso ogni stipendio nell'array
    nuovo_stipendio = stipendio * 2                          #Raddoppio stipendio corrente
    nuovi_stipendi.append(nuovo_stipendio)                   #Aggiungo nuovo stipendio alla lista

#Stampo nuovi stipendi raddoppiati, usando ciclo for
print("Stipendi raddoppiati con ciclo for:", nuovi_stipendi)  

Stipendi raddoppiati con ciclo for: [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]


In [8]:
#Con ciclo for, con una list comprehension
new_stipendi = [stipendio * 2 for stipendio in stipendi]    
print("Complimenti per il vostro lavoro, i nuovi stipendi sono:", new_stipendi)

Complimenti per il vostro lavoro, i nuovi stipendi sono: [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]


In [9]:
#Con masking di NumPy
nuovi_stipendi_masking = stipendi * 2                        #Raddoppio tutti stipendi nell'array, usando NumPy

#Stampo nuovi stipendi raddoppiati, usando masking 
print("Stipendi raddoppiati con masking:", nuovi_stipendi_masking)  

Stipendi raddoppiati con masking: [ 200  400  600  800 1000 1200 1400 1600 1800 2000]
